[package]
name = "wgpu"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
chip8 = { path = "../chip8" }
clap = { version = "4.5.28", features = ["derive"] }
env_logger = "0.11.6"
pixels = "0.15.0"
rodio = "0.20.1"
wgpu = "24.0.1"
winit = "0.30.9"
